### ISSUE TITLE
no fill or no advertisement

### ISSUE THREAD

**Issue by magic1983** [AppLovin/Android-SDK-Demo#14]
代码不能编译
Gradle sync failed: SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
				Consult IDE log for more details (Help | Show Log) (100ms)

**Comment by thomasmso** [comment]
Hello,

It looks like the `local.properties` file in your project does not contain the Android SDK path.

For example:

```
# local.properties
sdk.dir=/Users/magic1982/Library/Android/sdk
```
