### ISSUE TITLE
Xamarin Android Bindings

### ISSUE THREAD

**Issue by AndreasSchmid1** [AppLovin/Android-SDK-Demo#23]
I 'd like to use AppLovin in my Xamarin Android project. 
Do you support Xamarin Android?
Thx

**Comment by AndreasSchmid1** [comment]
that would be perfect. Thank you!

**Comment by smedasn** [comment]
i am interested as well

**Comment by smedasn** [comment]
the xamarin bindings repo was deleted?

**Comment by AndreasSchmid1** [comment]
any news?

**Comment by Drutol** [comment]
Hello, any progress with that?

**Comment by AntRemo** [comment]
Hi @thomasmso 

Has there been an progress on this?

Thanks

**Comment by thomasmso** [comment]
Hi @AntRemo - We have other higher priority projects in the pipeline. I will keep this in mind if one of my weekends free up (especially if more publishers request it).

**Comment by AntRemo** [comment]
Thanks @thomasmso  🙏

**Comment by igor-rif-shevchenko** [comment]
Hi @thomasmso do you have any updates?

**Comment by thomasmso** [comment]
Hi @AndreasSchmid1,  @smedasn, @tvfire, @Drutol, @AntRemo, @igor-rif-shevchenko - we decided against officially supporting it for now. I'd suggest pinging support@applovin.com to see if you can nudge the boat.

**Comment by thomasmso** [comment]
Closing - Please file a new issue [here](https://github.com/AppLovin/AppLovin-MAX-SDK-Android) if anyone is still interested in this.
