### ISSUE TITLE
Only fetch 1 Native ad

### ISSUE THREAD

**Issue by xiangjt** [AppLovin/Android-SDK-Demo#26]
I use nativeAdService.loadNativeAds to load 4 native ads, but wait several seconds, only loaded 1 native ad.
I try several times, but only can fetch 1 native ad, i don't know why?

I don't want preload Icon and Image, but it seems preload automatically, and icon url start file://, i want to know how to disable it, and every url start with http://

wait your reply!

**Comment by thomasmso** [comment]
That is correct behavior - we default to 1 native ad returned no matter how many you have requested now.

Also, it is default behavior for the SDK to cache the assets automatically - is there a reason why you don't want that?

**Comment by jitendrapurohit12** [comment]
Hey @thomasmso im also getting same issue with my recyclerview. it can only show one native add and i had requested 5. Can you please guide me how can i get more ads to render inside my recyclerview?

**Comment by thomasmso** [comment]
Hi @jitendrapurohit12 - again - we default to 1 native ad returned no matter how many you have requested now. If it is required that you have 1+ native ads, you will have to load them manually 1 at a time.

Also, closing the issue.

**Comment by xiangjt** [comment]
In some case, I only want to show ad icon, don't want show ad banner.
Preloaded banner seems useless.
