### ISSUE TITLE
More clear error message when the Applovin activities are missing from the AndroidManifest

### ISSUE THREAD

**Issue by guthyerrz** [AppLovin/Android-SDK-Demo#30]
So, in the android documentation is fine it clearly states that the `AppLovinInterstitialActivity` and `AppLovinConfirmationActivity`.  So my problem was that I was integrating with the `.unitypackage` release and these activities weren't added automatically to my app. When this happens the only error message that appear was `failed to show an ad`.

In the end I had to debug your SDK to find out what was wrong.

A more clear error code for this would be really helpful the next time.

**Comment by thomasmso** [comment]
Thanks for bringing this up - we'll add a more descriptive error message in the next release of the SDKs. Please let me know if there are any other concerns.
