### ISSUE TITLE
Interstitial failed to load with error code 204

### ISSUE THREAD

**Issue by 5z1punch** [AppLovin/Android-SDK-Demo#32]
No matter which kind of advertisement I load, it will return "Interstitial failed to load with error code 204". And I have turned on all of ads in my dashboard.

**Comment by thomasmso** [comment]
Hi - thanks for reaching out. [This article](https://monetization-support.applovin.com/hc/en-us/articles/115000509267-How-can-I-get-test-ads-) may help you. Let me know if that works.

**Comment by 5z1punch** [comment]
Hi, thanks very much. When I using a VPN connection to USA, I get ads. Maybe because I am in China now.I'm sorry for such a long time to reply.
