### ISSUE TITLE
Adding mandatory components to the library itself

### ISSUE THREAD

**Issue by ghost** [AppLovin/Android-SDK-Demo#33]
Hello Sirs,

If you distribute the library via Gradle, you can add mandatory components to its `AndroidManifest.xml` file, such as: permissions, activities... Those will be merged automatically into the host project when the developer builds it.

It will help with:

- Reducing details that a developer needs, when integrating your SDK.
- Reducing boilerplate code.
- Reducing possible mistakes, such as: copying/pasting, or adding `android:orientation` & `android:screenSize` to `AppLovinInterstitialActivity` for SDK >= 6.4.0...

On your side, it will help reduce problem such as the need of `android:orientation` and `android:screenSize` flags for `com.applovin.adview.AppLovinInterstitialActivity`. Since whenever you need to make any changes to your SDK, you can just go ahead and make those changes to the manifest file. It's just similar to Java code.

If you consider doing this, this might be a breaking change. As build tools will print some warning messages if the developer redefines those components in their own manifest. Please make notes when you release new version.

Thanks,

**Comment by thomasmso** [comment]
@all - Our latest Android SDK is distributed as an AAR, all you need to do is to add

```
implementation 'com.applovin:applovin-sdk:9.1.0'
```

into your app's `build.gradle` dependencies.
