### ISSUE TITLE
Adding com.applovin.apps.demoapp.nativeads.carouselui to official SDK

### ISSUE THREAD

**Issue by ghost** [AppLovin/Android-SDK-Demo#34]
Hello Sirs,

In the demo app, there is one package with a lot of code, both Java and xml resources (layout files...): `com.applovin.apps.demoapp.nativeads.carouselui`.

Currently developers have to copy them into their project. This might have some drawbacks:

- Mistakes.
- New SDK versions might have new demo code. So updating to new SDKs might force users to: delete old copies (exactly those files), and copy them again. This is _highly_ error-prone.

May I ask if you could add that package to official SDK?

Thank you,

**Comment by thomasmso** [comment]
Not included into our APIs due to several internal reasons.
