### ISSUE TITLE
Integrating your SDK is a pain

### ISSUE THREAD

**Issue by ghost** [AppLovin/Android-SDK-Demo#35]
Hello Sirs,

Are you professionals or amateurs? Integrating your SDK is a pain in the ass. I'm not even sorry.

Please put common things into the SDK. For example some UI controls in the demo app are perfect candidates.

You ask developers to change package names in xml layouts? Who are you? Amateurs?

If you put that in official SDK, your users won't have to deal with boilerplate code, copying/pasting... And your service will work better as a result.

Who are you? Amateurs or professionals?

I'm not looking forward to your highly-expected-amateur-response.

**Comment by thomasmso** [comment]
Not included into our APIs due to several internal reasons.
