### ISSUE TITLE
 AppLovinAdSize.INTERSTITIAL Duration Count

### ISSUE THREAD

**Issue by DeevD** [AppLovin/Android-SDK-Demo#38]
Request When ad is loading time count is not showing .

**Comment by thomasmso** [comment]
Could you please elaborate on the issue?

**Comment by DeevD** [comment]
i'm not sure that is issue or not . But  interstitial ad should be show ad duration count when playing ad video . That ad code is - > 

       AppLovinSdk.getInstance( this ).getAdService().loadNextAd( AppLovinAdSize.INTERSTITIAL, new AppLovinAdLoadListener()
        {
            @Override
            public void adReceived(AppLovinAd ad)
            {
                loadedAd = ad;
          
interstitialAd.showAndRender( loadedAd );

            }

            @Override
            public void failedToReceiveAd(int errorCode)
            {
                // Look at AppLovinErrorCodes.java for list of error codes.
            }
        } );
    }
}

**Comment by thomasmso** [comment]
Whether we show the duration count or not varies from creative to creative and cannot be controlled via our SDK.
