### ISSUE TITLE
Native Ads info

### ISSUE THREAD

**Issue by DeevD** [AppLovin/Android-SDK-Demo#39]
Native Ads is always return 1 count. code
_>

   private fun loadNativeAds() {
        val sdk = AppLovinSdk.getInstance(context)
        sdk.nativeAdService.loadNativeAds(4, object : AppLovinNativeAdLoadListener {
            override fun onNativeAdsLoaded(nativeAds: List<AppLovinNativeAd>) {
                nativeAds.forEach {
                    L.i(TAG, "Native Ad Loaded $it")
                    L.i(TAG, "native count ${nativeAds.count()}")
                        AppConstants.nativeAds.addAll(nativeAds)
                }
            }

            override fun onNativeAdsFailedToLoad(errorCode: Int) {
                // Native ads failed to load for some reason, likely a network error.
                // Compare errorCode to the available constants in AppLovinErrorCodes.

                if (errorCode == AppLovinErrorCodes.NO_FILL) {
                    // No ad was available for this placement
                }

            }
        })
    }

**Comment by thomasmso** [comment]
That is correct behavior, we will only return back one native ad even if the count is specified to be more.
