### ISSUE TITLE
com.applovin:applovin-sdk:9.3.0 has issues when I try to request Manifest.permission.WRITE_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by gubatron** [AppLovin/Android-SDK-Demo#42]
Something must have changed between `9.2.1` and `9.3.0`, now when I request `EXTERNAL_STORAGE_PERMISSIONS_REQUEST_CODE`/`Manifest.permission.WRITE_EXTERNAL_STORAGE` (which is needed for our app) It's denied.

If I revert to 9.2.1 permissions are granted by the system as always.

Any clue why this might be happening when using applovin `9.3.0`?

**Comment by thomasmso** [comment]
That's because in 9.3.0 we added back a missing permission in the Android Manifest of our SDK's AAR:

```
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="18" />
```

We only explicitly need the permission in < API 19 for video ads caching.

**Comment by gubatron** [comment]
yes, I noticed that in the docs. But then when you write "android:maxSdkVersion=18' and you're running on say Android 8.0 (api 26) and up, growing fast on popularity, and other features of your app need that permission, my guess is that the manifest isn't requesting such permission unless the device's API <= 18 and then my app stops working properly on newer OSes.

am I understanding `android:maxSdkVersion="18"` right? and what could be a work around. 

AppLovin is our predominant advertising SDK and we're active on nearly 1MM/daily devices, and we'd like to keep you guys well updated.

**Comment by santoshbagadi** [comment]
Hi @gubatron 

Our SDK does not need `android.permission.WRITE_EXTERNAL_STORAGE` for API 19+ (Android also requires the app to request the user for this permission on 19+).

If other features of your app require this permission, you would need to override our requirement by using `tools:remove="attr, ..."` [attribute marker](https://developer.android.com/studio/build/manifest-merge#attribute_markers) in your `AndroidManifest.xml`. Here is how it can be used with the external storage permission:
```
    <uses-permission
        android:name="android.permission.WRITE_EXTERNAL_STORAGE"
        tools:remove="android:maxSdkVersion" />
```

Please let us know if it works for you.

**Comment by gubatron** [comment]
Thank you for the quick answer @santoshbagadi and @thomasmso .
It seems the `tools:remove=` didn't do the trick. Still not getting `WRITE_EXTERNAL_STORAGE` permission with `9.3.0`

![Screen Shot 2019-03-15 at 7 16 51 PM](https://user-images.githubusercontent.com/163977/54468912-0d289100-4757-11e9-9e29-7c5da67a2a77.png)

Wonder if there's any other workaround, I bet I'm not going to be the only one that needs `WRITE_EXTERNAL_STORAGE` in your user base.

**Comment by gubatron** [comment]
that did it!

![Screen Shot 2019-03-15 at 7 20 23 PM](https://user-images.githubusercontent.com/163977/54468944-6abcdd80-4757-11e9-9b87-5b4fa451f020.png)

Love you guys! AppLovin team rocks.

**Comment by gubatron** [comment]
(make sure to include this in the [android docs](https://dash.applovin.com/docs/integration#androidIntegration), some note for users that do need the permissions)

**Comment by thomasmso** [comment]
Thanks @santoshbagadi for the save! @gubatron thanks for the suggestion - not going to lie, our docs are a bit rusty right now as we've moved all our focus over to our MAX header bidding solution.
