### ISSUE TITLE
JNI DETECTED ERROR IN APPLICATION: JNI FindClass called with pending exception java.net.SocketException: Software caused connection abort

### ISSUE THREAD

**Issue by goyourfly** [AppLovin/Android-SDK-Demo#43]
SDK version: 9.3.0

Hello, Sometimes the network state changes cause the app to crash,

[This is the error log](https://github.com/AppLovin/Android-SDK-Demo/files/3021560/error.txt)

 I guess it should be the crash caused here.

![image](https://user-images.githubusercontent.com/7019862/55216045-ad41e800-5236-11e9-9174-56f840cc7e0b.png)

**Comment by goyourfly** [comment]
Close because it's Android os problem

**Comment by YYDBA** [comment]
I found that this bug must be found when Samsung's mobile phone is disconnected. How can I deal with it? Thank you
