### ISSUE TITLE
how to add applovin.sdk.key programmable

### ISSUE THREAD

**Issue by sahujaunpuri** [AppLovin/Android-SDK-Demo#44]
how to add applovin.sdk.key programmable ?
becoz I have need to create an extension for the app inventor source code.
there was no option to add "< meta-data
            android:name="applovin.sdk.key"
            android:value="YOUR_SDK_KEY"   />" in xml file

**Comment by thomasmso** [comment]
Another way would be do do something like this:

```
final AppLovinSdk appLovinSdk = AppLovinSdk.getInstance( "SDK_KEY", new AppLovinSdkSettings( context ), context );
```
