### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by ghost** [AppLovin/Android-SDK-Demo#45]
Hello developers.

Thank you for your overengineered-complicated sdk. When you put the brilliant Carousel UI in demo app, it is really a brilliant idea.

- I have to copy and paste, and then rename package, and then look for your comments in xml layout to rename package.

- There are a lot of handy-work. So for each customer, I have to charge more and more. I make a lot of money from my customers. No other developers can compete with me.

Thanks for you 80' sdk. It is well designed. After all, it helps me earn money.

Please add more and more and more complicated stuff in your demo. Please don't move those stuff into the sdk. I'm begging you, please _do not_ move those stuff from demo into sdk. Let me just copy and paste them, and then rename package, and then look into xml layout to rename pakcage.

Thanks again Sirs, your 80' sdk is really great. Prior to applovin, you Sirs must have been working at google, right? You are very talented developers.

Thank you Sirs,

**Comment by thomasmso** [comment]
Hi,

Our SDKs (native ads especially) are designed with extensibility in mind. The carousel UI is only one of many implementations of native ads - to include all of them into the SDK would be infeasible.

Many regards,
Thomas
