### ISSUE TITLE
Android Banner Ads Not Working 

### ISSUE THREAD

**Issue by Abhijith4124** [AppLovin/Android-SDK-Demo#47]
Hi,
The Banner Ads Does not seem to Work For me, Am I Doing Something wrong? Thanks
I have Initialized Like this : 
private AppLovinAdView bannerView;

bannerView = new AppLovinAdView(AppLovinAdSize.BANNER, activity);

bannerView.setAdLoadListener(new AppLovinAdLoadListener(){
      @Override
      public void adReceived(final AppLovinAd ad){
        BannerAdLoaded();
      }

      @Override
      public void failedToReceiveAd(final int errorCode){
        BannerAdFailedToLoad(errorCode);
      }
    });

Then Load the Ad Like this : 
public void LoadBannerAd(AndroidViewComponent component){
    ViewGroup viewGroup = (ViewGroup) component.getView();

    if (bannerView.getParent() != null) {
      viewGroup.removeView(bannerView);
    }

    viewGroup.addView(bannerView, new android.widget.FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT, Gravity.CENTER));

    bannerView.loadNextAd();
  }

Thanks

**Comment by thomasmso** [comment]
Do you mind reproducing the issue with our SDK's [verbose logging enabled](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-can-I-expose-verbose-logging-for-the-SDK-) and sending the logs over? 
Also, it will be easier if you just follow one of the banner examples [here](https://github.com/AppLovin/Android-SDK-Demo/tree/master/Android-Demo-App/src/main/java/com/applovin/apps/demoapp/banners).

**Comment by Abhijith4124** [comment]
> Do you mind reproducing the issue with our SDK's [verbose logging enabled](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-can-I-expose-verbose-logging-for-the-SDK-) and sending the logs over?
> Also, it will be easier if you just follow one of the banner examples [here](https://github.com/AppLovin/Android-SDK-Demo/tree/master/Android-Demo-App/src/main/java/com/applovin/apps/demoapp/banners).

I cant Add Meta Data because I am Making an Extension For AppInventor. 
I Initialize the SDK like this : 
appLovinSdk = AppLovinSdk.getInstance(sdkKey, new AppLovinSdkSettings(context), context);

The Interstitial Ad Works Fine While banner and Reward Ads Doesn't work.

**Comment by thomasmso** [comment]
Try checking your AppLovin UI and turning on these ad formats. Also, we have a programmatic way of turning on verbose logging (: :

```
final AppLovinSdk sdk = AppLovinSdk.getInstance( sdkKey, new AppLovinSdkSettings( context ), context );
sdk.getSettings().setVerboseLogging( true );
```

**Comment by Abhijith4124** [comment]
I think the problem is because the banner and Reward Ads doesn't use AppLovin sdk instance. The Interstitial ad receives the appLovinSdk Instance. It would be helpful if there is a way to initialize the banner and Reward ads from the appLovinSdk Instance.

Thanks, I'll send the logs too

**Comment by thomasmso** [comment]
Both banners and rewarded ads actually have APIs to use a custom AppLovin SDK instance that does not take its SDK key from the Android Manifest. See below:

AppLovinAdView.java:
```
public AppLovinAdView(final AppLovinSdk sdk, final AppLovinAdSize adSize, final Context context)
```

AppLovinIncentivizedInterstitial.java:
```
public static AppLovinIncentivizedInterstitial create(final AppLovinSdk sdk)
```

**Comment by Abhijith4124** [comment]
Thank You So Much, It Was the Solution. It would be Nice if those API is mentioned in the SDK Documentation.

Thank You For your Time.

**Comment by Abhijith4124** [comment]
Also, One More Question. Which is the API For UserConsent and AgeRestricted Blocks? Thanks

**Comment by thomasmso** [comment]
Here is the [documentation](https://dash.applovin.com/docs/integration#androidPrivacySettings) for Android privacy settings.

**Comment by Abhijith4124** [comment]
Does it need AppLovinSDK Instance? Thanks

**Comment by thomasmso** [comment]
Nope it will automatically detect and update all instances of our SDKs that are in memory.

**Comment by Abhijith4124** [comment]
Okay, Thanks.
