### ISSUE TITLE
Proguard doesn't optimize code

### ISSUE THREAD

**Issue by And808** [AppLovin/Android-SDK-Demo#48]
Hi,
I've updated AppLovin sdk from 8.1.4 version 
(implementation "com.applovin:applovin-sdk:8.1.4")
to 9.6.2
(implementation "com.applovin:applovin-sdk:9.6.2@aar")
and now Proguard doesn't optimize application code.

ProGuard version 5.3.3
[proguard-rules.pro](https://gist.github.com/And808/04a11aed213eb3b787b62d2c83fb7ea8)

AppLovin version 8.1.4. assembleRelease task output:
Shrinking...
Printing usage to [/.../app/build/outputs/mapping/release/usage.txt]...
Removing unused program classes and class elements...
  Original number of program classes: 1713
  Final number of program classes:    622
Optimizing...
...
Shrinking...
Removing unused program classes and class elements...
  Original number of program classes: 622
  Final number of program classes:    605
Obfuscating...

AppLovin version 9.6.2. assembleRelease task output:
Shrinking...
Printing usage to [/.../app/build/outputs/mapping/release/usage.txt]...
Removing unused program classes and class elements...
  Original number of program classes: 1917
  Final number of program classes:    1206
Obfuscating...

**Comment by thomasmso** [comment]
Thanks for reporting this issue. Our latest Android SDK has an option for not optimizing in its ProGuard configuration file. It will be fixed in the next SDK release (v9.7.0).

**Comment by thomasmso** [comment]
Closing, as Android SDK 9.7.0 has been released on May 27th.
