### ISSUE TITLE
Another way would be do do something like this:

### ISSUE THREAD

**Issue by sahujaunpuri** [AppLovin/Android-SDK-Demo#50]
Another way would be do do something like this:

```
final AppLovinSdk appLovinSdk = AppLovinSdk.getInstance( "SDK_KEY", new AppLovinSdkSettings( context ), context );
```

_Originally posted by @thomasmso in https://github.com/AppLovin/Android-SDK-Demo/issues/44#issuecomment-484220604_

when im use in android studio 

`final AppLovinSdk appLovinSdk =
                AppLovinSdk.getInstance( "EGHL5i8CTBb78Dg_KK0XH642hCJ4umqDp4SMZfBUTT66OaufwPFB-1q__u_4fKudyGwb6HBxewIE4M7IvikP9R",
                new AppLovinSdkSettings( this ), this );`

its not working 

also when im using in extension 
![applovin](https://user-images.githubusercontent.com/22550065/62802363-595cdf00-bb05-11e9-850e-59abe9c1503c.png)

his also not woring

**Comment by santoshbagadi** [comment]
Hi @sahujaunpuri ,

Would you mind providing the error you are getting when using this.

**Comment by thomasmso** [comment]
Closing, as no response has been provided.

**Comment by sahujaunpuri** [comment]
hi @santoshbagadi there are no error show during run-time.
only ads not showing . if i add in manifest file manually `< meta-data
android:name="applovin.sdk.key"
android:value="YOUR_SDK_KEY" />`

then ads showing

**Comment by thomasmso** [comment]
@sahujaunpuri - You need to replace `"YOUR_SDK_KEY"` with your AppLovin SDK key. You can find it in your AppLovin dashboard under "Account" -> "Keys" -> "SDK Key".

**Comment by sahujaunpuri** [comment]
Yes yes 
That's I do
But ads not showing if I add key programbly
If I add key in manifestfile then ads show. 

My basic need add key programbly for app inventor builders extensions 
I hope now u get my problems 
.

**Comment by thomasmso** [comment]
Can you show us your code snippet for how you are loading and showing ads?

**Comment by sahujaunpuri** [comment]
> Can you show us your code snippet for how you are loading and showing ads?

thats i cont here . i can mail u . if u send me ur mail id 
my mail id is shivendrakumarsahu@gmail.com

**Comment by thomasmso** [comment]
Feel free to send it over to thomas.so@applovin.com

**Comment by sahujaunpuri** [comment]
> Feel free to send it over to [thomas.so@applovin.com](mailto:thomas.so@applovin.com)

thanks 
i send u mail

**Comment by mohamad62** [comment]
I have the same problem, how did you fix it?
