### ISSUE TITLE
Applovin Banner Disappears in recyclerView  

### ISSUE THREAD

**Issue by ameerhamzaconsoliads** [AppLovin/Android-SDK-Demo#53]
Banner Ad displays when show first time in recycler View but after scroll the banner view disappears from the list. I think the sdk destroys the banner after the parent view is removed during the scroll.

**Comment by thomasmso** [comment]
Do you mind setting auto destroy to `false` in `public void setAutoDestroy(final boolean isAutoDestroy)` of `AppLovinAdView`?

**Comment by ameerhamzaconsoliads** [comment]
Thanks @thomasmso it worked. I spend whole day on this but didn't find the answer.
