### ISSUE TITLE
NullPointException When Initializing the SDK

### ISSUE THREAD

**Issue by Abhijith4124** [AppLovin/Android-SDK-Demo#54]
I am initializing the SDK Like this...

```
final AppLovinSdk appLovinSdk = AppLovinSdk.getInstance( "SDK_KEY", new AppLovinSdkSettings( context ), context );
```

_Originally posted by @thomasmso in https://github.com/AppLovin/Android-SDK-Demo/issues/44#issuecomment-484220604_

This method does not work in the latest SDK but works in the older ones. I tried 9.10.3 and 9.11.1, It does not work.

Any Solution? Thanks

**Comment by thomasmso** [comment]
Hey @Abhijith4124 - Do you mind sending me the stack trace so I can start debugging for you? Thanks!

**Comment by thomasmso** [comment]
Hey @Abhijith4124 - Was wondering if you received my last message?

**Comment by Abhijith4124** [comment]
Yes, I received it. Sorry for the delay. Will send it soon

**Comment by thomasmso** [comment]
@Abhijith4124 - Ty. I'll be awaiting for the crash report. Alternatively you can email me at thomas.so@applovin.com. Thank you.
