### ISSUE TITLE
NPE in sdk

### ISSUE THREAD

**Issue by OlegTarashkevich** [AppLovin/Android-SDK-Demo#58]
Hi,

@tiandrew @thomasmso 

The app crashes after adding android applovin sdk v.9.12.0

I can't reproduce on my test devices, but users have the crash.

<img width="1102" alt="Screen Shot 2020-04-25 at 19 57 27" src="https://user-images.githubusercontent.com/13828110/80285702-5fe0c480-872f-11ea-81a0-77cdec8b0040.png">

<img width="1114" alt="Screen Shot 2020-04-25 at 19 57 09" src="https://user-images.githubusercontent.com/13828110/80285698-5ce5d400-872f-11ea-8183-96b2586899ee.png">

**Comment by thomasmso** [comment]
Hi @OlegTarashkevich - I'd love to help you, do you mind sharing a full crash report with me at thomas.so@applovin.com? I'd love to see what the other threads are doing during the crash. Thanks!

**Comment by OlegTarashkevich** [comment]
Thanks for the answer @thomasmso 
Just sent a crash report to your email, please check.
I temporary disabled the sdk, while is not clear how to fix.

**Comment by thomasmso** [comment]
Conversed via email - fixed in latest Android SDK.
