### ISSUE TITLE
运行该Demo，无法加载原生广告

### ISSUE THREAD

**Issue by landis-zou** [AppLovin/Android-SDK-Demo#59]
下载该Demo并成功将应用安装到手机上，
1、本地Mainifest的配置applovin.sdk.key已修改为自己上的key
2、后台已开启测试模式
但点击无法加载出Nathan Ads-Single ad，显示errorcode为204，nofill

**Comment by angelwu0409** [comment]
@landis-zou 您好，
Error code 204表示当前没有广告填充，有可能有以下原因：
1. VPN IP 问题 - 您是否使用了VPN来拉取测试广告？如果在后台打开了测试模式，可以关闭VPN直接拉取广告；如果没有打开测试模式，可以使用其他VPN去美国/日本等广告填充充足等地区看是否能够直接拉到广告。
2. 如果1无法解决您的问题，可以给我们提供verbose log：
https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-can-I-expose-verbose-logging-for-the-SDK-

谢谢！

**Comment by thomasmso** [comment]
Closing issue - please refer to readme for new GitHub repo.
