### ISSUE TITLE
Samsung mobile phone will crash when it is network disconnected

### ISSUE THREAD

**Issue by YYDBA** [AppLovin/Android-SDK-Demo#60]
this bug is same as this issues [https://github.com/AppLovin/Android-SDK-Demo/issues/43#issue-426857664]
android version:8.0.0
mobile model:samsung s7
sdk version:9.12.4
please help

**Comment by thomasmso** [comment]
Hi @YYDBA - Do you have a stack trace of the crash we can look at?

**Comment by YYDBA** [comment]
@thomasmso hi,this is my log
[log.txt](https://github.com/AppLovin/Android-SDK-Demo/files/4612883/log.txt)

**Comment by thomasmso** [comment]
Thanks @YYDBA, one of our engineers, @Lorenzo45, will be looking at it and update the thread.

**Comment by YYDBA** [comment]
hi @thomasmso I found that the wrong time in the mobile phone system can cause this problem, which may help

**Comment by thomasmso** [comment]
@YYDBA - That tip is much appreciated. Thank you!

**Comment by thomasmso** [comment]
The fix has been released in Android SDK v9.12.7.

**Comment by YYDBA** [comment]
@thomasmso thank you
