### ISSUE TITLE
Broken Applovin Banner Ads on Mopub Mediation 

### ISSUE THREAD

**Issue by davidmaraba** [AppLovin/Android-SDK-Demo#62]
I'm loading Applovin Banner Ads via Mopub Mediation but most times they are broken as shown in the attached image. Kindly advise.

Libraries used.

    implementation 'com.applovin:applovin-sdk:9.13.0'
    implementation 'com.mopub.mediation:applovin:9.13.0.0'
![broken_applovin](https://user-images.githubusercontent.com/3704786/88778257-f4c0e700-d190-11ea-819b-31afd8fa5a32.png)

**Comment by thomasmso** [comment]
Hey @davidmaraba - thanks for reporting this - do you mind [enabling our SDK's verbose logs](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-can-I-expose-verbose-logging-for-the-SDK-) and sending it over to devsupport@applovin.com for analysis?

**Comment by davidmaraba** [comment]
> devsupport@applovin.com

Done.

**Comment by davidmaraba** [comment]
Hello @thomasmso when is this likely to be fixed?

**Comment by thomasmso** [comment]
Hey @davidmaraba - we're working on it, likely by EoW.

**Comment by thomasmso** [comment]
@davidmaraba - Sorry for late update but this has been fixed a while back now.
