### ISSUE TITLE
Always error code 204

### ISSUE THREAD

**Issue by dipankar108** [AppLovin/Android-SDK-Demo#63]
I have set up ads on my apps but interstitial ads working fine and showing but banner ads its always show me error code 204 even on test mode.
               AppLovinSdk.initializeSdk(MainActivity.this);
               AppLovinAdView bannerad=new AppLovinAdView(AppLovinAdSize.BANNER,this);
               ViewGroup viewGroup=findViewById(android.R.id.content);
               viewGroup.addView(bannerad);
               bannerad.setLayoutParams(new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT,Gravity.BOTTOM));
               bannerad.loadNextAd();
               adView.setAdLoadListener( new AppLovinAdLoadListener()
               {

                   @Override
                   public void adReceived(final AppLovinAd ad)
                   {
                       Log.d("TAGA", "adReceived: true");

                   }

                   @Override
                   public void failedToReceiveAd(final int errorCode)
                   {
                       // Look at AppLovinErrorCodes.java for list of error codes
                       Log.d("TAGA", "adReceived: bannerads not recieved "+errorCode);
                   }
               } );

**Comment by thomasmso** [comment]
Hi,

Please use [test mode](https://dash.applovin.com/documentation/mediation/android/testing-networks/test-mode) to get fill for AppLovin banner ads as they likely will not fill in development environments.
